version: '3.2'

services:
  node_app:
    build:
      context: .
    environment:
      - PORT=3000
      - DB_CONNECTION_STRING=mongodb://mongo/development_db
    restart: always
    command: ./node_modules/nodemon/bin/nodemon.js --tls-min-v1.0 src/app.js
    volumes:
      - ./src:/code/src

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017

  nginx:
    image: nginx:1.21.1
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
